// All the questions live here. Add, edit, or remove questions freely.
// Each theme has a name, a color, a short "brief" (used when asking Claude for new questions), and a list of cards.

window.TALK_CARDS = {
  freedom: {
    name: "Freedom and Movement", color: "var(--freedom)",
    brief: "travel, moving, free time, independence, places, going out, staying in",
    cards: [
      "What does vulnerability mean to you?",
      "Do you drink alcohol? Why or why not?",
      "Can you be friends with someone who holds completely opposite political views from you?",
      "How do you define self love?",
      "What's the best advice you've received and from whom?",
      "What is one of your biggest fears?",
      "Have you ever stereotyped anyone based on their physical appearance? Explain.",
      "Should Marijuana be legal?",
      "How do you define freedom?",
      "Is there anything you take for granted in life?",
      "If time and money were no object, where would you take your dream vacation? Why?",
      "Would you be open to talking to a therapist about your problems?",
      "How often do you shower or bathe?",
      "Are you bluntly honest with people, even if your words are potentially hurtful?",
      "Have you ever considered physically harming yourself? If so, why?",
      "How do you define success?",
      "On a scale of 1 - 10, how would you rate your self confidence? Explain.",
      "What are some of the biggest misconceptions people have about your race, ethnicity or tribe?",
      "If you could have one superpower, what would it be and what would you use it for?",
      "Are you creative? Why or why not? How do you express that creativity?",
      "What do you love most about your personality?",
      "What books have you read lately?",
      "Is mental health important and how do you maintain it?",
      "What are your religious views?",
      "Is crying a sign of weakness?",
      "Should abortion be legal?"
    ]
  },
  deal: {
    name: "Dealbreakers", color: "var(--deal)",
    brief: "small habits, pet peeves, lifestyle differences, what someone could or could not put up with, controversial topics like religion, politics, feminism etc",
    cards: [
      "You discover that your partner engaged in sexual activities in exchange for money. The experience happened only once long before you met each other. Is this a deal breaker?",
      "Your partner must undergo a bodily surgery that will prevent them from having sex with you for atleast 12 months. Is this a deal breaker?",
      "Your partner, in the past, has been intimate with someone of the same sex (in the case of opposite couples) or opposite sex (in the cae of same sex couples). Is that a deal breaker?",
      "When in a good mood, your partner is sweet, kind, and treats you like royalty. However, when in a bad mood or extremely upset with you, your partner has a tendency to yell, throw objects, and punch walls. Is this a deal breaker?",
      "While on a date with your significant other, you run into an old friend whom you haven't spoken to in years. After introducing the old friend to your partner, you discover that they already know each other. Later on, your partner reveals that they slept with the old friend, long before you two met. Is this a deal breaker? Why or why not?",
      "In a relationship, do you consider constant breakups and make-ups a deal breaker?",
      "Your partner develops a serious prescription drug addiction after sustaining work related bodily injury. The addiction has begun to hinder their ability to effectively earn a living. Is this a deal breaker?",
      "You are in a serious relationship with your partner, and both are considering engagement. Before doing so, your partner wants to schedule a date for you two to visit divorce court and observe failed marriages. Is this a deal breaker?",
      "You and your partner have been in a committed relationship together for 8 months. You are both happy, and see the relationship blossoming long term. However, you've recently discovered that you are third cousins. Is this a deal breaker?",
      "After dating seriously for over a year, your partner adamantly expresses a desire to accept a job offer in a another country that would require immediate relocation. Is this a dealbreaker?",
      "You and your partner have been in a committed relationship for a year and you find out they have committed a felony or two in the past. Is this a deal breaker?",
      "You've been in a committed relationship for two months and have had unprotected sex with your partner atkeast once or twice. One day you decide to visit a VCT for fun and the results show that one of you has HIV. Is this a deal breaker?",
      "Your partner seems to have a stronger emotional connection with their best friend, but promises you that their relationship is purely platonic. Is this a deal breaker?"
    ]
  },
  intimacy: {
    name: "Intimacy", color: "var(--intimacy)",
    brief: "desire, vulnerability, what turns you on emotionally and sexually, fears about getting close, honest and a little flirty, sex games",
    cards: [
      "In a serious relationship/marriage, is your partner obligated to have sex with you?",
      "Do you verbally express satisfaction or displeasure during sexual intercourse?",
      "Do you have any sexual fetishes, and if so, what are they?",
      "Do you set a certain time frame before engaging in sexual activities with new partners?",
      "What are some ways to be intimate with your mate without having sex?",
      "Have you ever faked an orgasm, and if so, why?",
      "How do you respond when your partner doesn't orgasm during sex?",
      "How do you determine consent before engaging in sexual activity?",
      "Would you be comfortable knowing that your partner had more sexual partners than you?",
      "Are you okay dating someone who is celibate?",
      "When were you last tested for STDs?",
      "Where's the strangest place you've had sex/masturbated?",
      "What is a 'G spot', and where is it located?",
      "On a weekly basis, how often do you prefer to have sex?",
      "How do you 'set the mood' for your partner?",
      "Do you enjoy cuddling?",
      "Do you possess any physical characteristics that cause sexual insecurities or shyness in the bedroom?",
      "Would you be concerned if your partner still masturbated, even though you were sexually active together?",
      "Do you consider masturbation a shameful act?",
      "Are you comfortable kissing your partner immediately after they've performed oral sex on you?",
      "Is connecting emotionally before having sex important to you?",
      "Do you believe in soul ties? Explain.",
      "Name one sex fact you know as an adult, but wish you'd learned earlier in life",
      "Do you need to know about your partner's previous sexual history?",
      "Is oral sex important to you?",
      "Are you comfortable initiating sex, or would you prefer your partner to do so?",
      "How do you feel about public sex?",
      "How do you feel about condoms? How often do you use them?",
      "Are you okay having casual sex? Explain why/why not.",
      "What is you're worst experience during coitus?"
    ]
  },
  love: {
    name: "Love and Relationships", color: "var(--love)",
    brief: "dates, showing affection, romance, traditions, advice about love, sweet and playful",
    cards: [
      "What physical qualities attract you to a mate?",
      "In a relationship, should contact with previous partners completely discontinue?",
      "What character qualities attract you to a mate?",
      "What is your biggest red flag when searching for a partner?",
      "Would you consider dating someone whose religion or spirituality is the primary focus in their life?",
      "Do you consider interracial/ intertribal dating taboo?",
      "How do you define cheating?",
      "What would you say or do if your date cried while watching your first movie together?",
      "Could you love someone you've never met in person?",
      "In a serious relationship, do you feel it's important to dkeep your significant other informed of the details of your day-to-day life?",
      "Is jealousy healthy in a relationship?",
      "Would you consider dating someone you share the same learning/work environment with(coursemate/workmate)? Elaborate.",
      "Have you ever initiated a breakup in a previous relationship, and why?",
      "How do you handle heartbreak?",
      "What's the worst date you've gone on? Describe it.",
      "How do you feel about long distance relationships?",
      "What were some of the major issues in past relationships, and what have you learned about yourself from those experiences?",
      "How would you react if your partner's best friend expressed attraction and came on to you?",
      "What's more important to you, being with someone who is more financially stable, or someone you can build and grow with?",
      "Do you believe in monogamy?",
      "Is age just a number, and why?",
      "How would you expect your partner to respond if someone were flirting with you in their presence?",
      "Are you comfortable going out to a club with your significant other?",
      "How do you feel about pet names in a relationship?",
      "What are some signs that let you know someone is flirting with you?",
      "In a relationship, what are your preferred methods of giving and receiving affection?",
      "Who should pay on the first date?",
      "Are you comfortable farting in front of your partner? How long does it take to gain this comfort?",
      "Are you comfortable with your partner making more or less money than you? Does their gender matter?"
    ]
  }
};
